import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#1f2937', // gray-800
              color: '#fff',
              border: '1px solid #374151', // gray-700
            },
            success: {
              iconTheme: {
                primary: '#10b981', // green-500
                secondary: '#fff',
              },
            },
            error: {
              iconTheme: {
                primary: '#ef4444', // red-500
                secondary: '#fff',
              },
            },
            loading: {
              iconTheme: {
                primary: '#3b82f6', // blue-500
                secondary: '#fff',
              },
            },
          }}
        />        {children}
      </body>
    </html>
  );
}
